### ISSUE TITLE
Some Language_ID in CLDF pics datasets have additional numbers 

### ISSUE THREAD

**Issue by ekmakhlina** [cldf-datasets/apics#14]
Hi,

Looking through data at https://github.com/cldf-datasets/apics/blob/master/cldf/values.csv#L1111 I discovered that some Language_IDs use additional numbers in the beginning or in the end of ID, for example 1201 for 20 in the 1110 line. I did not find anything about that in CLDF documentation, though this occurs several times in the data. Do not sure if it is an actual issue, considering data displayed correctly on the site, but just in case I decided to mention it here.

**Comment by xrotwang** [comment]
The language IDs are correct! For some varieties, the APiCS project also collected some data for sociolects. These sociolects typically have a four-digit ID, see for example https://github.com/cldf-datasets/apics/blob/master/cldf/languages.csv#L4-L6

**Comment by ekmakhlina** [comment]
Thank a lot, sorry for bothering!

**Comment by xrotwang** [comment]
Btw. this is described here: https://github.com/cldf-datasets/apics/blob/f687a830a62aa5e16ad1b5d477e92d6307c10e6f/cldf/StructureDataset-metadata.json#L507-L508
